### ISSUE TITLE
update all the subsystems and commands

### ISSUE THREAD

**Issue by matunkar** [LakotaRobotics1038/2024RobotProject#57]
this will invalidate some of the open prs. its ok. 

subsystems
- [x] acquisition should have two motors, a motor called `sushiMotor` and a `intakeMotor`. they should be separate and have separate methods, one to run (with a constant speed) .
- [x]  the laser should be a digital input laser called `acqLaser` with a get method. this was done in issue #45  just steal from that branch
- [x] scoring should have three motors. a `leftElevatorMotor` and `rightElevatorMotor`. it should also have a `rollerMotor`. it should NOT have a loadingMotor. that will be moved. 
- [x] the left and right elevator motors should have all the methods they need. the rollerMotor should have the ability to roll backwards and forwards at constant speeds (dont pass in a parameter). this was done in issue #41 just steal from that branch.
- [x] storage should have 3 motors. a left and right storage motor and a transition motor. the LR motors should be mirroreed and synchronized. the transition should be separate. all should have methods to run backwards and forwards at constant speeds. 
- [x] storage should also have two lasers! a top one and a bottom one, with get methods. this is similar to what was added in issue #45 but there should actually be two in storage and none in scoring. 
- [x] lift should have two motors. a left and a right. it should also have a left and right servo. this was already done in issue #54 just steal from that.

 commands
update each of the commands they will all have errors. probably
there should be:
- [x] a command to run the acquisition intake forward - it should stop running after the acqLaser no longer sees the note (up for debate)
- [x] a command to run it backwards
- [x] similar commands for the acquisition sushi roller, but no laser input
- [x] a command to set the position of the scoring lift system
- [x] a command to run the scoring roller forwards - runs off a timer
- [x] a command to run the scoring roller backwards (to shoot) - runs off a timer, only shoots if the position is the amp height or high
- [x] a command to run the transition motor - stops once the first storage laser stops detecting a note
- [x] a command to run the storage motors - stops once the second storage laser stops detecting a note (debatable, might run off a timer after the first positive sensor return)
- [x] reverse both the storage and transition motors
- [x] commands to run the lift up and down
(update later)
